require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.1
  Exclude:
    - db/schema.rb
    - db/migrate/20240310084931_create_doorkeeper_tables.rb
    - config/environments/*
    - bin/*

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false
